### PR TITLE
[OSFUSE-413]open probes port 8081 for springboot-cxf-jaxws quickstarts

### PR DESCRIPTION
**Pull request by ffang**

### CODE REVIEW

**Comment by ffang** [comment]
[merge]

**Comment by ffang** [comment]
[merge][lgtm]

**Comment by ffang** [comment]
@rawlingsj  
Could you please merge this one? Seems I can't trigger the Jenkins CI node to build and merge now, though I can do it about two weeks ago.
Thanks for your help!

**Comment by nicolaferraro** [comment]
ok to test

**Comment by nicolaferraro** [comment]
[merge]

**Comment by nicolaferraro** [comment]
@ffang I'm now trying to align the fis-2.0.x.redhat branch as we pushed a lot of commit only to the master. We should update the fis branch first (the FIS 2.0 pipeline uses that branch).

**Comment by ffang** [comment]
@nicolaferraro  thanks!

**Pull request merged**
